name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      

    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: 'docker-flask-react'
          
    - name: Load Docker Compose File and Spin Up Containers
      run: |
        cd  C:/projects/DMGPT
        docker-compose up -d
        
    - name: List Running Containers
      run: |
        docker ps
        
    - name: Check http://localhost:3000/
      run: |
        $retryCount = 0
        $maxRetries = 5
        $url = "http://localhost:3000/"
        
        do {
          try {
            $response = Invoke-WebRequest -Uri $url -UseBasicParsing
            if ($response.StatusCode -eq 200) {
              Write-Host "Successfully reached $url"
              break
            } else {
              Write-Host "Received status code $($response.StatusCode) from $url"
            }
          } catch {
            Write-Host "Failed to reach $url. Retrying in 10 seconds..."
            Start-Sleep -Seconds 10
            $retryCount++
          }
        } while ($retryCount -lt $maxRetries)

        if ($retryCount -eq $maxRetries) {
          throw "Failed to reach $url after $maxRetries retries."
        }
