on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest # Changed to a Linux runner since it's more common and well-supported for Docker

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: 'docker-flask-react'
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
          
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Set up Docker Compose
      run: |
        docker-compose up -d

    - name: Wait for application to be ready
      run: |
        sleep 60 # Waiting for application to start. Consider using a more robust way to wait for your specific application.

    - name: Check application
      run: |
        curl http://localhost:3000 || exit 1
